# Generated by Django 4.0.5 on 2022-07-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
