# Generated by Django 4.0.5 on 2022-07-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_address_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_deegre', models.CharField(max_length=100)),
                ('doctor_speciality', models.CharField(max_length=100)),
                ('doctor_fee', models.CharField(max_length=100)),
                ('doctor_start_time', models.CharField(max_length=100)),
                ('doctor_end_time', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
