# Generated by Django 4.0.5 on 2022-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_doctor_profile_doctor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='doctor_address',
            field=models.TextField(),
        ),
    ]
