# Generated by Django 4.0.5 on 2022-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_appoiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoiment',
            name='status',
            field=models.CharField(default='pendding', max_length=100),
        ),
    ]
