# Generated by Django 4.0.5 on 2022-07-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cancleappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorcancleappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_issue', models.TextField()),
                ('appoinments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appoiment')),
            ],
        ),
    ]
