# Generated by Django 4.0.5 on 2022-07-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_doctorcancleappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorcancleappointment',
            old_name='cancel_issue',
            new_name='issue',
        ),
    ]
