# Generated by Django 4.0.4 on 2022-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoiment',
            name='fees_status',
            field=models.CharField(default='pendding', max_length=100),
        ),
    ]
