# Generated by Django 4.0.4 on 2022-07-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_appoiment_fees_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appoiment',
            new_name='Appointment',
        ),
    ]
