# Generated by Django 4.0.4 on 2022-07-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_appoiment_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cancleappointment',
            new_name='cancelappointment',
        ),
        migrations.RenameModel(
            old_name='doctorcancleappointment',
            new_name='doctorcancelappointment',
        ),
        migrations.RenameField(
            model_name='cancelappointment',
            old_name='appoinments',
            new_name='appointments',
        ),
        migrations.RenameField(
            model_name='doctorcancelappointment',
            old_name='appoinments',
            new_name='appointments',
        ),
    ]
