# Generated by Django 4.0.4 on 2022-07-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_cancleappointment_cancelappointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressuer', models.BooleanField(default=False)),
                ('blood_group', models.CharField(max_length=100)),
                ('diabetes', models.BooleanField(default=False)),
                ('allergy', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
