# Generated by Django 4.0.4 on 2022-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_healthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='weights',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
